name: CI

on:
  push:
  pull_request:

jobs:
  deterministic-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          elixir-version: "1.18.3"

      - name: Fetch dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Run deterministic tests
        run: mix test --exclude external
